create table amhs_configurations(
id                  		        serial primary key,
channel_name        		        varchar(255) NOT NULL UNIQUE,
tsap_format                         varchar(5) NOT NULL,
tsap                                varchar(50) NOT NULL,
channel_type                        varchar(50) NOT NULL,
protocol                            varchar(5) NOT NULL,
transport_type                      varchar(10) NOT NULL,
associations                        int NOT NULL,
bind_type                           varchar(50) NOT NULL,
server_name                         varchar(255) NOT NULL,
port_number                         int NOT NULL,
disconnect_on_timeout               bool NOT NULL,
connection_timeout                  int NOT NULL,
service_class                       varchar(50) NOT NULL,
latest_delivery_time                bool NOT NULL,
dl_expansion_prohibited             bool NOT NULL,
content_correlator                  bool NOT NULL,
recipient_reassignment_prohibited   bool NOT NULL,
local_supervisor_address            varchar(255) NOT NULL,
remote_supervisor_address           varchar(255) NOT NULL,
incoming_directory                  varchar(255) NOT NULL,
outgoing_directory                  varchar(255) NOT NULL,
version                             bigint DEFAULT 0 NOT NULL,
created_at                          timestamp with time zone NOT NULL DEFAULT now(),
created_by                          varchar(50) NOT NULL,
updated_at                          timestamp with time zone,
updated_by                          varchar(50)
);
