
-- 01 ====  WAYPOINT insertion  =====================================================================================================================

-- 02 ====  'UL776' AIRWAY update  ====  Source: ATFM SYSTEM CUSTOMIZATIONS AF.pdf  =================================================================

-- 03 ====  'UL452' AIRWAY insertion  ====  Source: ATFM SYSTEM CUSTOMIZATIONS AF.pdf  ==============================================================

-- 04 ====  'UL462' AIRWAY update  ====  Source: ATFM SYSTEM CUSTOMIZATIONS AF.pdf  =================================================================

-- 05 ====  'UL576' AIRWAY insertion  ====  Source: ATFM SYSTEM CUSTOMIZATIONS AF.pdf  ==============================================================

-- 06 ====  'UB540' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 75781  =======================================================

-- 07 ====  'G653' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 75860  ========================================================

-- 08 ====  'UA409' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 75861  =======================================================

-- 09 ====  'UM214' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 75844  =======================================================

-- 10 ====  'UM315' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 91182  =======================================================

-- 11 ====  'UP312' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 91182  =======================================================

-- 12 ====  ADHP insertion  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 70290  ==============================================================

-- 13 ====  'UT916' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Nov. 09, 2017  =====================================================

-- 14 ====  ADHP insertion  ====  Source: WIKIPEDIA  ====  Comment: TFS 94885  ======================================================================

-- 15 ====  ADHP insertion  ====  Source: WIKIPEDIA  ====  Comment: TFS 94884  ======================================================================
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.092847', '-17.931806'), 4326), '31.092847','-17.931806','FVRG','ROBERT GABRIEL MUGABE INTL','idsna','wikipedia','FVRG','WGE','4901.0','FT') RETURNING "airport_pk";

-- 16 ====  ADHP insertion  ====  Source: WIKIPEDIA  ====  Comment: Observed by k.gubbins while analyzing KCAA data  ================================
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('34.822498', '-2.45806'), 4326), '34.822498','-2.45806','HTSN','SERONERA AIRSTRIP','idsna','http://ourairports.com','HTSN','WGE','5080.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('47.454444', '6.780833'), 4326), '47.454444','6.780833','HCMR','ABDULLAHI YUSUF / GALKAYO','idsna','http://ourairports.com','HCMR','WGE','975.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('38.001833', '-7.748241'), 4326), '38.001833','-7.748241','HTBB','KIBAMBAWE AIRSTRIP','idsna','https://airportguide.com','HTBB','WGE','485.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('48.577778', '8.466667'), 4326), '48.577778','8.466667','HCGR','NEW GAROWE AIRPORT (MUGLOTAGTAG)','idsna','https://skyvector.com','HCGR','WGE','1500.0','FT') RETURNING "airport_pk";
update airport set validto = '2018-10-24T00:00:00'::timestamp without time zone where ident = 'HC0006';
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('29.566999', '3.233'), 4326), '29.566999','3.233','FZJB','DOKO','idsna','http://www.gcmap.com','FZJB','WGE','2874.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('42.311667', '2.330556'), 4326), '42.311667','2.330556','HCMD','BARDERA','idsna','http://www.gcmap.com','HCMD','WGE','4200.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('38.1367', '-7.6847'), 4326), '38.1367','-7.6847','HTZW','SIWANDU','idsna','http://www.pilotnav.com','HTZW','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('44.784722', '2.672222'), 4326), '44.784722','2.672222','HCIX','BALEDOGLE','idsna','wikipedia','HCIX','WGE',NULL,'FT') RETURNING "airport_pk";

-- 17 ====  ADHP insertion  ====  Source: WIKIPEDIA  ====  Comment: Observed by d.panech while analyzing KCAA data  =================================
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('28.57674', '3.597484'), 4326), '28.57674','3.597484','FZJC','DUNGU-UYE','idsna','http://ourairports.com','FZJC','WGE','2378.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('-17.073333333', '14.67'), 4326), '-17.073333333','14.67','GOBD','DIASS-THIES BLAISE DIAGNE INTL','idsna','http://ourairports.com','GOBD','WGE','290.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('49.083', '9.517'), 4326), '49.083','9.517','HCMG','GARDO','idsna','http://ourairports.com','HCMG','WGE','2632.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('47.345556', '8.5675'), 4326), '47.345556','8.5675','HCMP','LAS ANOD','idsna','http://www.gcmap.com','HCMP','WGE','2077.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('35.063611', '-1.29861'), 4326), '35.063611','-1.29861','HKMZ','MUSIARA','idsna','http://www.gcmap.com','HKMZ','WGE','5200.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('35.617', '-3.433'), 4326), '35.617','-3.433','HKNN','NGORO NGORO','idsna','http://www.gcmap.com','HKNN','WGE','4600.0','FT') RETURNING "airport_pk";

-- 18 ====  WAYPOINT insertion  ====  Source: j.nicolaas@dc-ansp.org  ====  Comment: see also misc_scripts/2018-09-26--curacao-waypoint/  ===========
INSERT INTO navdb.waypoint (waypoint_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codetype, codedatum) VALUES ((SELECT MAX(waypoint_pk) + 1 FROM navdb.waypoint), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('-71.85', '12.81666667'), 4326), '-71.85','12.81666667','AMBAS','AMBAS','idsna','dc-ansp.org','ICAO','WGE') RETURNING "waypoint_pk";
