
-- 01 ====  WAYPOINT insertion  ====  Comment: Missing waypoints for Botswana  ======================================================================

-- 02 ====  ADHP insertion  ====  Source: ICAO ICARD 5LNC  ====  Comment: TFS 70290  ================================================================

-- 03 ====  ADHP insertion  ====  Source: WIKIPEDIA  ====  Comment: Observed by k.gubbins while analyzing KCAA data  ================================

-- 04 ====  ADHP insertion  ====  Source: WIKIPEDIA  ====  Comment: Observed by d.panech while analyzing KCAA data  =================================

-- 05 ====  ADHP insertion  ====  Source: w.reiche@idscorporation.com  ====  Comment: TFS 101774  ===================================================

-- 06 ====  ADHP insertion  ====  Source: w.reiche@idscorporation.com  ====  Comment: TFS 105875 South Sudan  =======================================
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.6011166666667', '4.87200555555556'), 4326), '31.6011166666667','4.87200555555556','HJJJ','JUBA','idsna','http://ourairports.com','HJJJ','WGE','1513.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.6522416666667', '9.55896944444445'), 4326), '31.6522416666667','9.55896944444445','HJMK','MALAKAL','idsna','http://ourairports.com','HJMK','WGE','1291.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('29.4188622222222', '6.82979361111111'), 4326), '29.4188622222222','6.82979361111111','HJRB','RUMBEK','idsna','http://ourairports.com','HJRB','WGE','1378.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('27.97495', '7.72574722222222'), 4326), '27.97495','7.72574722222222','HJWW','WAU','idsna','http://ourairports.com','HJWW','WGE','1529.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('32.959444', '10.053611'), 4326), '32.959444','10.053611','HJAR','ADAREIL','idsna','http://ourairports.com','HJAR','WGE','1301.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.412659', '7.45405'), 4326), '31.412659','7.45405','HJAJ','AJUINI','idsna','http://ourairports.com','HJAJ','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('33.0027', '7.7779'), 4326), '33.0027','7.7779','HJAK','AKOBO','idsna','http://ourairports.com','HJAK','WGE','1352.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('27.4', '8.767'), 4326), '27.4','8.767','HJAW','AWEIL','idsna','http://ourairports.com','HJAW','WGE','1394.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.407251', '8.130524'), 4326), '31.407251','8.130524','HJAY','AYOD','idsna','http://ourairports.com','HJAY','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.600485', '6.195865'), 4326), '31.600485','6.195865','HJBR','BOR','idsna','http://ourairports.com','HJBR','WGE','1394.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.428108', '8.010956'), 4326), '31.428108','8.010956','HJBK','BUK','idsna','http://ourairports.com','HJBK','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.451797', '7.600151'), 4326), '31.451797','7.600151','HJDK','DUK KWENYAKWO','idsna','http://ourairports.com','HJDK','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.514969', '7.477794'), 4326), '31.514969','7.477794','HJDP','DUK PAYUEL','idsna','http://ourairports.com','HJDP','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('29.157161', '4.791895'), 4326), '29.157161','4.791895','HJBB','IBBA','idsna','http://ourairports.com','HJBB','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('33.583', '4.783'), 4326), '33.583','4.783','HJKP','KAPOETA','idsna','http://ourairports.com','HJKP','WGE','2220.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('32.062225', '8.528016'), 4326), '32.062225','8.528016','HJLK','LANKIEN','idsna','http://ourairports.com','HJLK','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('35.8328', '5.288'), 4326), '35.8328','5.288','HJLW','LOKWOR','idsna','http://ourairports.com','HJLW','WGE','1415.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('29.466999', '4.917'), 4326), '29.466999','4.917','HJMD','MARIDI','idsna','http://ourairports.com','HJMD','WGE','1901.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.333179', '8.415234'), 4326), '31.333179','8.415234','HJMG','MOGOK','idsna','http://ourairports.com','HJMG','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('30.346927', '5.359401'), 4326), '30.346927','5.359401','HJMI','MUNDRI WEST','idsna','http://ourairports.com','HJMI','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('29.956666', '6.06388'), 4326), '29.956666','6.06388','HJMV','MVOLO','idsna','http://ourairports.com','HJMV','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('32.132999', '3.617'), 4326), '32.132999','3.617','HJNM','NIMULE','idsna','http://ourairports.com','HJNM','WGE','2059.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('28.26757', '4.635486'), 4326), '28.26757','4.635486','HJNZ','NZARA','idsna','http://ourairports.com','HJNZ','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('32.500556', '10.529167'), 4326), '32.500556','10.529167','HJPH','PALOICH','idsna','http://ourairports.com','HJPH','WGE','1290.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.422261', '7.329981'), 4326), '31.422261','7.329981','HJPG','PANYAGOR','idsna','http://ourairports.com','HJPG','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.838636', '8.069767'), 4326), '31.838636','8.069767','HJPA','PATHAI','idsna','http://ourairports.com','HJPA','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('33.130556', '6.793333'), 4326), '33.130556','6.793333','HJPB','PIBOR','idsna','http://ourairports.com','HJPB','WGE','1377.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('32.029867', '8.041298'), 4326), '32.029867','8.041298','HJPR','PIERI','idsna','http://ourairports.com','HJPR','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.948328', '8.596297'), 4326), '31.948328','8.596297','HJPU','PULTURUK','idsna','http://ourairports.com','HJPU','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('25.681101', '8.46111'), 4326), '25.681101','8.46111','HJRG','RAGA','idsna','http://ourairports.com','HJRG','WGE','1788.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('32.810497', '11.832469'), 4326), '32.810497','11.832469','HJRK','RENK','idsna','http://ourairports.com','HJRK','WGE','1278.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('28.983', '7.267'), 4326), '28.983','7.267','HJTN','TONG','idsna','http://ourairports.com','HJTN','WGE','1413.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('32.583', '4.4'), 4326), '32.583','4.4','HJTR','TORIT','idsna','http://ourairports.com','HJTR','WGE','2050.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('27.450001', '5.6'), 4326), '27.450001','5.6','HJTB','TUMBURA','idsna','http://ourairports.com','HJTB','WGE','2230.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.967554', '7.988008'), 4326), '31.967554','7.988008','HJTU','TURUK','idsna','http://ourairports.com','HJTU','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('32.153184', '8.189679'), 4326), '32.153184','8.189679','HJWT','WAAT','idsna','http://ourairports.com','HJWT','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('28.423901', '4.56722'), 4326), '28.423901','4.56722','HJYB','YAMBIO','idsna','http://ourairports.com','HJYB','WGE','2375.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('30.728073', '4.130282'), 4326), '30.728073','4.130282','HJYE','YEI','idsna','http://ourairports.com','HJYE','WGE','2000.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('30.5', '6.567'), 4326), '30.5','6.567','HJYL','YIROL','idsna','http://ourairports.com','HJYL','WGE','1424.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.887646', '7.905764'), 4326), '31.887646','7.905764','HJYU','YUAI','idsna','http://ourairports.com','HJYU','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('29.816999', '9.217'), 4326), '29.816999','9.217','HJBT','BENTIU','idsna','http://ourairports.com','HJBT','WGE','2000.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.400299', '7.739314'), 4326), '31.400299','7.739314','HJDF','DUK PADIET','idsna','http://ourairports.com','HJDF','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.691265', '7.746628'), 4326), '31.691265','7.746628','HJPJ','PAJUT','idsna','http://ourairports.com','HJPJ','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('34.097359', '7.178563'), 4326), '34.097359','7.178563','HJPO','POCHALLA','idsna','http://ourairports.com','HJPO','WGE','2000.0','FT') RETURNING "airport_pk";
