package ca.ids.abms.modules.spatiareader.entity;

// Generated Aug 12, 2014 11:23:44 AM by Hibernate Tools 4.0.0

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.util.Date;
import java.util.List;

/**
 * FplObject generated by hbm2java
 */
@Entity
@Table(name = "fpl_object", schema = "ais")
public class FplObject implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long catalogueFplObjectId;
	private Date catalogueDate;
	private String catalogueStatus;
	private String catalogueTxStatus;
	private String cataloguePrcStatus;
	private Date catalogueExpiryDate;
	private String comOriginator;
	private String comDstAddrList;
	private String comOptionalField;
	private String flightId;
	private String ssrMode;
	private String ssrCode;
	private String flightRules;
	private String flightType;
	private String aircraftNumber;
	private String aircraftType;
	private String wakeTurb;
	private String equipment;
	private String departureAd;
	private String departureTime;
	private String msgDepartureAd;
	private String msgDepartureTime;
	private String speed;
	private String flightLevel;
	private String route;
	private String destinationAd;
	private String totalEet;
	private String alternateAd;
	private String alternateAd2;
	private String arrivalAd;
	private String arrivalTime;
	private String arrAerodrome17;
	private String otherInfo;
	private Date departureDate;
	private Date arrivalDate;
	private Date cancelationDate;
	private Date lastChangeDate;
	private Date delayDate;
	private Date dayOfFlight;
	private String gufi;
	private Integer userId;
	private Date childMessageMaxCatalogueDate;
    private String rawFpl;
    private List<CplObject> cplObjects;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "child_message_max_catalogue_date", nullable = false, length = 22)
	public Date getChildMessageMaxCatalogueDate() {
		return childMessageMaxCatalogueDate;
	}

	public void setChildMessageMaxCatalogueDate(Date childMessageMaxCatalogueDate) {
		this.childMessageMaxCatalogueDate = childMessageMaxCatalogueDate;
	}

	public FplObject() {
	}

	public FplObject(long catalogueFplObjectId,
                     Date catalogueDate, String catalogueStatus,
                     String catalogueTxStatus, String cataloguePrcStatus,
                     String comOriginator, String flightId, String departureAd,
                     String departureTime, String destinationAd, Date dayOfFlight) {
		this.catalogueFplObjectId = catalogueFplObjectId;
		this.catalogueDate = catalogueDate;
		this.catalogueStatus = catalogueStatus;
		this.catalogueTxStatus = catalogueTxStatus;
		this.cataloguePrcStatus = cataloguePrcStatus;
		this.comOriginator = comOriginator;
		this.flightId = flightId;
		this.departureAd = departureAd;
		this.departureTime = departureTime;
		this.destinationAd = destinationAd;
		this.dayOfFlight = dayOfFlight;
	}

	public FplObject(long catalogueFplObjectId,
                     Date catalogueDate, String catalogueStatus,
                     String catalogueTxStatus, String cataloguePrcStatus,
                     Date catalogueExpiryDate, String comOriginator,
                     String comDstAddrList, String comOptionalField, String flightId,
                     String ssrMode, String ssrCode, String flightRules,
                     String flightType, String aircraftNumber, String aircraftType,
                     String wakeTurb, String equipment, String departureAd,
                     String departureTime, String msgDepartureAd,
                     String msgDepartureTime, String speed, String flightLevel,
                     String route, String destinationAd, String totalEet,
                     String alternateAd, String alternateAd2, String arrivalAd,
                     String arrivalTime, String arrAerodrome17, String otherInfo,
                     Date departureDate, Date arrivalDate, Date cancelationDate,
                     Date lastChangeDate, Date delayDate, Date dayOfFlight, String gufi,
                     Integer userId, String rawFpl) {
		this.catalogueFplObjectId = catalogueFplObjectId;
		this.catalogueDate = catalogueDate;
		this.catalogueStatus = catalogueStatus;
		this.catalogueTxStatus = catalogueTxStatus;
		this.cataloguePrcStatus = cataloguePrcStatus;
		this.catalogueExpiryDate = catalogueExpiryDate;
		this.comOriginator = comOriginator;
		this.comDstAddrList = comDstAddrList;
		this.comOptionalField = comOptionalField;
		this.flightId = flightId;
		this.ssrMode = ssrMode;
		this.ssrCode = ssrCode;
		this.flightRules = flightRules;
		this.flightType = flightType;
		this.aircraftNumber = aircraftNumber;
		this.aircraftType = aircraftType;
		this.wakeTurb = wakeTurb;
		this.equipment = equipment;
		this.departureAd = departureAd;
		this.departureTime = departureTime;
		this.msgDepartureAd = msgDepartureAd;
		this.msgDepartureTime = msgDepartureTime;
		this.speed = speed;
		this.flightLevel = flightLevel;
		this.route = route;
		this.destinationAd = destinationAd;
		this.totalEet = totalEet;
		this.alternateAd = alternateAd;
		this.alternateAd2 = alternateAd2;
		this.arrivalAd = arrivalAd;
		this.arrivalTime = arrivalTime;
		this.arrAerodrome17 = arrAerodrome17;
		this.otherInfo = otherInfo;
		this.departureDate = departureDate;
		this.arrivalDate = arrivalDate;
		this.cancelationDate = cancelationDate;
		this.lastChangeDate = lastChangeDate;
		this.delayDate = delayDate;
		this.dayOfFlight = dayOfFlight;
		this.gufi = gufi;
		this.userId = userId;
        this.rawFpl=rawFpl;
	}

	@Id
	@Column(name = "catalogue_fpl_object_id", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCatalogueFplObjectId() {
		return this.catalogueFplObjectId;
	}

	public void setCatalogueFplObjectId(long catalogueFplObjectId) {
		this.catalogueFplObjectId = catalogueFplObjectId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "catalogue_date", nullable = false, length = 22)
	public Date getCatalogueDate() {
		return this.catalogueDate;
	}

	public void setCatalogueDate(Date catalogueDate) {
		this.catalogueDate = catalogueDate;
	}

	@Column(name = "catalogue_status", nullable = false, length = 1)
	public String getCatalogueStatus() {
		return this.catalogueStatus;
	}

	public void setCatalogueStatus(String catalogueStatus) {
		this.catalogueStatus = catalogueStatus;
	}

	@Column(name = "catalogue_tx_status", nullable = false, length = 1)
	public String getCatalogueTxStatus() {
		return this.catalogueTxStatus;
	}

	public void setCatalogueTxStatus(String catalogueTxStatus) {
		this.catalogueTxStatus = catalogueTxStatus;
	}

	@Column(name = "catalogue_prc_status", nullable = false, length = 1)
	public String getCataloguePrcStatus() {
		return this.cataloguePrcStatus;
	}

	public void setCataloguePrcStatus(String cataloguePrcStatus) {
		this.cataloguePrcStatus = cataloguePrcStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "catalogue_expiry_date", length = 22)
	public Date getCatalogueExpiryDate() {
		return this.catalogueExpiryDate;
	}

	public void setCatalogueExpiryDate(Date catalogueExpiryDate) {
		this.catalogueExpiryDate = catalogueExpiryDate;
	}

	@Column(name = "com_originator", nullable = false, length = 8)
	public String getComOriginator() {
		return this.comOriginator;
	}

	public void setComOriginator(String comOriginator) {
		this.comOriginator = comOriginator;
	}

	@Column(name = "com_dst_addr_list", length = 2000)
	public String getComDstAddrList() {
		return this.comDstAddrList;
	}

	public void setComDstAddrList(String comDstAddrList) {
		this.comDstAddrList = comDstAddrList;
	}

	@Column(name = "com_optional_field", length = 54)
	public String getComOptionalField() {
		return this.comOptionalField;
	}

	public void setComOptionalField(String comOptionalField) {
		this.comOptionalField = comOptionalField;
	}

	@Column(name = "flight_id", nullable = false, length = 7)
	public String getFlightId() {
		return this.flightId;
	}

	public void setFlightId(String flightId) {
		this.flightId = flightId;
	}

	@Column(name = "ssr_mode", length = 1)
	public String getSsrMode() {
		return this.ssrMode;
	}

	public void setSsrMode(String ssrMode) {
		this.ssrMode = ssrMode;
	}

	@Column(name = "ssr_code", length = 4)
	public String getSsrCode() {
		return this.ssrCode;
	}

	public void setSsrCode(String ssrCode) {
		this.ssrCode = ssrCode;
	}

	@Column(name = "flight_rules", length = 1)
	public String getFlightRules() {
		return this.flightRules;
	}

	public void setFlightRules(String flightRules) {
		this.flightRules = flightRules;
	}

	@Column(name = "flight_type", length = 2)
	public String getFlightType() {
		return this.flightType;
	}

	public void setFlightType(String flightType) {
		this.flightType = flightType;
	}

	@Column(name = "aircraft_number", length = 2)
	public String getAircraftNumber() {
		return this.aircraftNumber;
	}

	public void setAircraftNumber(String aircraftNumber) {
		this.aircraftNumber = aircraftNumber;
	}

	@Column(name = "aircraft_type", length = 4)
	public String getAircraftType() {
		return this.aircraftType;
	}

	public void setAircraftType(String aircraftType) {
		this.aircraftType = aircraftType;
	}

	@Column(name = "wake_turb", length = 1)
	public String getWakeTurb() {
		return this.wakeTurb;
	}

	public void setWakeTurb(String wakeTurb) {
		this.wakeTurb = wakeTurb;
	}

	@Column(name = "equipment", length = 100)
	public String getEquipment() {
		return this.equipment;
	}

	public void setEquipment(String equipment) {
		this.equipment = equipment;
	}

	@Column(name = "departure_ad", nullable = false, length = 4)
	public String getDepartureAd() {
		return this.departureAd;
	}

	public void setDepartureAd(String departureAd) {
		this.departureAd = departureAd;
	}

	@Column(name = "departure_time", nullable = false, length = 4)
	public String getDepartureTime() {
		return this.departureTime;
	}

	public void setDepartureTime(String departureTime) {
		this.departureTime = departureTime;
	}

	@Column(name = "msg_departure_ad", length = 4)
	public String getMsgDepartureAd() {
		return this.msgDepartureAd;
	}

	public void setMsgDepartureAd(String msgDepartureAd) {
		this.msgDepartureAd = msgDepartureAd;
	}

	@Column(name = "msg_departure_time", length = 4)
	public String getMsgDepartureTime() {
		return this.msgDepartureTime;
	}

	public void setMsgDepartureTime(String msgDepartureTime) {
		this.msgDepartureTime = msgDepartureTime;
	}

	@Column(name = "speed", length = 5)
	public String getSpeed() {
		return this.speed;
	}

	public void setSpeed(String speed) {
		this.speed = speed;
	}

	@Column(name = "flight_level", length = 5)
	public String getFlightLevel() {
		return this.flightLevel;
	}

	public void setFlightLevel(String flightLevel) {
		this.flightLevel = flightLevel;
	}

	@Column(name = "route", length = 1800)
	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	@Column(name = "destination_ad", nullable = false, length = 4)
	public String getDestinationAd() {
		return this.destinationAd;
	}

	public void setDestinationAd(String destinationAd) {
		this.destinationAd = destinationAd;
	}

	@Column(name = "total_eet", length = 4)
	public String getTotalEet() {
		return this.totalEet;
	}

	public void setTotalEet(String totalEet) {
		this.totalEet = totalEet;
	}

	@Column(name = "alternate_ad", length = 4)
	public String getAlternateAd() {
		return this.alternateAd;
	}

	public void setAlternateAd(String alternateAd) {
		this.alternateAd = alternateAd;
	}

	@Column(name = "alternate_ad_2", length = 4)
	public String getAlternateAd2() {
		return this.alternateAd2;
	}

	public void setAlternateAd2(String alternateAd2) {
		this.alternateAd2 = alternateAd2;
	}

	@Column(name = "arrival_ad", length = 4)
	public String getArrivalAd() {
		return this.arrivalAd;
	}

	public void setArrivalAd(String arrivalAd) {
		this.arrivalAd = arrivalAd;
	}

	@Column(name = "arrival_time", length = 1800)
	public String getArrivalTime() {
		return this.arrivalTime;
	}

	public void setArrivalTime(String arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	@Column(name = "arr_aerodrome_17", length = 30)
	public String getArrAerodrome17() {
		return this.arrAerodrome17;
	}

	public void setArrAerodrome17(String arrAerodrome17) {
		this.arrAerodrome17 = arrAerodrome17;
	}

	@Column(name = "other_info", length = 1800)
	public String getOtherInfo() {
		return this.otherInfo;
	}

	public void setOtherInfo(String otherInfo) {
		this.otherInfo = otherInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "departure_date", length = 22)
	public Date getDepartureDate() {
		return this.departureDate;
	}

	public void setDepartureDate(Date departureDate) {
		this.departureDate = departureDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "arrival_date", length = 22)
	public Date getArrivalDate() {
		return this.arrivalDate;
	}

	public void setArrivalDate(Date arrivalDate) {
		this.arrivalDate = arrivalDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cancelation_date", length = 22)
	public Date getCancelationDate() {
		return this.cancelationDate;
	}

	public void setCancelationDate(Date cancelationDate) {
		this.cancelationDate = cancelationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_change_date", length = 22)
	public Date getLastChangeDate() {
		return this.lastChangeDate;
	}

	public void setLastChangeDate(Date lastChangeDate) {
		this.lastChangeDate = lastChangeDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delay_date", length = 22)
	public Date getDelayDate() {
		return this.delayDate;
	}

	public void setDelayDate(Date delayDate) {
		this.delayDate = delayDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "day_of_flight", nullable = false, length = 22)
	public Date getDayOfFlight() {
		return this.dayOfFlight;
	}

	public void setDayOfFlight(Date dayOfFlight) {
		this.dayOfFlight = dayOfFlight;
	}

	@Column(name = "gufi", length = 30)
	public String getGufi() {
		return this.gufi;
	}

	public void setGufi(String gufi) {
		this.gufi = gufi;
	}

	@Column(name = "user_id", precision = 6, scale = 0)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

    @Column(name = "raw_fpl", length = 4000 )
    public String getRawFpl() {
        return rawFpl;
    }

    public void setRawFpl(String rawFpl) {
        this.rawFpl = rawFpl;
    }

    @OneToMany(mappedBy="flightObjectId", targetEntity=CplObject.class)
	@Fetch(FetchMode.SELECT)
	public List<CplObject> getCplObjects() {
		return cplObjects;
	}

	public void setCplObjects(List<CplObject> cplObjects) {
		this.cplObjects = cplObjects;
	}

    @Override
    public int hashCode() {
        int result = (int) (catalogueFplObjectId ^ (catalogueFplObjectId >>> 32));
        result = 31 * result + (flightId != null ? flightId.hashCode() : 0);
        result = 31 * result + (departureAd != null ? departureAd.hashCode() : 0);
        result = 31 * result + (departureTime != null ? departureTime.hashCode() : 0);
        result = 31 * result + (dayOfFlight != null ? dayOfFlight.hashCode() : 0);
        return result;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (!(o instanceof FplObject)) {
            return false;
        }
        return catalogueFplObjectId == ((FplObject) o).getCatalogueFplObjectId();
    }


    @Override
    public String toString() {
        return "FplObject{" +
            "catalogueFplObjectId=" + catalogueFplObjectId +
            ", flightId='" + flightId + '\'' +
            ", dayOfFlight=" + dayOfFlight +
            ", departureAd='" + departureAd + '\'' +
            ", departureTime='" + departureTime + '\'' +
            '}';
    }
}
