image: maven:3.3.9-jdk-8

stages:
    - build
    - deploy

# Build only
build:
    stage: build
    script:
        - mvn package -Dmaven.repo.local=/cache --settings=$PWD/settings.xml --batch-mode --update-snapshots -DskipTests

# Build and deploy on tag/push
deploy:
    stage: deploy
    only:
        - /^v[0-9][0-9.]+$/
    script:
        - mvn deploy -Dmaven.repo.local=/cache --settings=$PWD/settings.xml --batch-mode -DaltDeploymentRepository=deploy::default::$MAVEN_DEPLOY_REPO --update-snapshots -DskipTests