package ca.ids.abms.config.db;

public enum CriteriaType {
    NOT_EQUAL,
    LIKE,
    EQUAL,
    EQUAL_SECOND,
    OR_EQUAL,
    BETWEEN,
    BETWEEN_COLUMNS,
    NOT_BETWEEN_COLUMNS,
    GREATER_THAN,
    GREATER_OR_EQUAL_THAN,
    GREATER_OR_EQUAL_THAN_TIME,
    GREATER_THAN_DATE_TIME,
    LESS_THAN_DATE_TIME,
    LESS_OR_EQUAL_THAN_TIME,
    GREATER_THAN_DISTINCT,
    LESS_THAN,
    LESS_OR_EQUAL_THAN,
    LESS_THAN_DISTINCT,
    NOT_NULL,
    NOT_NULL_DISTINCT,
    IS_NULL,
    IS_NOT_EMPTY,
    IN,
    OR
}
