-- Alter table flight_movements
alter table flight_movements add column item18_rmk varchar(255);
alter table flight_movements add column atc_log_track public.geometry(Geometry,4326);
alter table flight_movements add column tower_log_track public.geometry(Geometry,4326);
alter table flight_movements add column atc_crossing_distance numeric(10,2);
alter table flight_movements add column tower_crossing_distance numeric(10,2);
alter table flight_movements add column user_crossing_distance numeric(10,2);
alter table flight_movements add column atc_crossing_distance_cost numeric(10,2);
alter table flight_movements add column tower_crossing_distance_cost numeric(10,2);
alter table flight_movements add column user_crossing_distance_cost numeric(10,2);
alter table flight_movements add column enroute_charges_basis varchar(30);
alter table flight_movements add column late_charges numeric(10,2);
alter table flight_movements add column parking_time numeric(10,2);
alter table flight_movements add column domestic_passenger_charges numeric(10,2);
alter table flight_movements add column international_passenger_charges numeric(10,2);
alter table flight_movements add column exempt_enroute_charges numeric(10,2);
alter table flight_movements add column exempt_approch_charges numeric(10,2);
alter table flight_movements add column exempt_dep_charges numeric(10,2);
alter table flight_movements add column exempt_late_charges numeric(10,2);
alter table flight_movements add column exempt_parking_charges numeric(10,2);
alter table flight_movements add column exempt_domestic_passenger_charges numeric(10,2);
alter table flight_movements add column exempt_international_passenger_charges numeric(10,2);
alter table flight_movements add column enroute_charges_status varchar(20);
alter table flight_movements add column passenger_charges_status varchar(20);
alter table flight_movements add column other_charges_status varchar(20);
alter table flight_movements add column enroute_invoice_id int;
alter table flight_movements add column passenger_invoice_id int;
alter table flight_movements add column other_invoice_id int;
alter table flight_movements add column delta_flight bool not null default false;
alter table flight_movements add column resolution_errors int default 0;
alter table flight_movements add column source varchar(20) not null default '';
alter table flight_movements add column manually_changed_fields int;
