update system_configurations set range = '0,100' where item_name = 'Domestic passenger fee percentage';
update system_configurations set range = '0,100' where item_name = 'International passenger fee percentage';
update system_configurations set range = '0,60' where item_name = 'Entry/exit point rounding distance';
update system_configurations set range = '-90,90' where item_name = 'Map north latitude';
update system_configurations set range = '-90,90' where item_name = 'Map centre height';
update system_configurations set range = '-90,90' where item_name = 'Map south latitude';
update system_configurations set range = '-180,180' where item_name = 'Map east longitude';
update system_configurations set range = '-180,180' where item_name = 'Map west longitude';
update system_configurations set range = '-90,90' where item_name = 'Map centre latitude';
update system_configurations set range = '-90,90' where item_name = 'Map centre longitude';
update system_configurations set range = '365,maxint' where item_name = 'ATC movement logs retention';
update system_configurations set range = '365,maxint' where item_name = 'Flight movement retention';
update system_configurations set range = '365,maxint' where item_name = 'Line item retention';
update system_configurations set range = '365,maxint' where item_name = 'User event log retention';
update system_configurations set range = '0,5' where item_name = 'Flight leg decimal places';
update system_configurations set range = '0,2' where item_name = 'Logging level';
update system_configurations set range = '0,30000' where item_name = 'Radar floor level';
update system_configurations set range = '1,maxint' where item_name = 'Route caching retention';
update system_configurations set range = '1,maxint' where item_name = 'Automated upload scheduling';
update system_configurations set range = '0,200' where item_name = 'Percentage of EET to be used for flight match';
update system_configurations set range = '0,120' where item_name = 'Minimum range for flight match';
update system_configurations set range = '1025,65536' where item_name = 'Radar summary port number';
update system_configurations set range = '0,100' where item_name = 'Mock fatal error occurrence frequency';
update system_configurations set range = '0,200' where item_name = 'Percentage of EET to detect duplicate flights';
update system_configurations set range = '1,1440' where item_name = 'Cached event retry interval';
update system_configurations set range = '0,120' where item_name = 'Minimum window to detect duplicate flights';
update system_configurations set range = '0,32' where item_name = 'Password minimum length';
update system_configurations set range = '10,1000' where item_name = 'Number of rows per page';

DELETE FROM system_configurations WHERE item_name IN ('Map centre latitude', 'Map centre longitude', 'Map centre height');