# vim:ts=4:sts=4:sw=4:et:
stages:
    - rpm-build
    - rpm-push

# For feature branches build RPM without compression (faster) and discard the RPM
rpm-build:
    # This image is maintaned in abms/docker-abms-devel project in GitLab and is a
    # minimal CentOS 7 image with tools required for creating and deploying RPM packages
    image: docker-reg.idscorporation.ca/abms/centos-builder:generic
    stage: rpm-build
    except:
        # develop branches are handled in a separate job below
        - /^develop(-.*)?$/
    script:
        - cd rpm && COMPRESS=0 ./build.sh

# For develop-* branches build RPM with full compression and save the RPM for "rpm-push" stage
rpm-build:
    # This image is maintaned in abms/docker-abms-devel project in GitLab and is a
    # minimal CentOS 7 image with tools required for creating and deploying RPM packages
    image: docker-reg.idscorporation.ca/abms/centos-builder:generic
    stage: rpm-build
    only:
        - /^develop(-.*)?$/
    script:
        - export PACKAGE_QUALIFIER=$(echo "$CI_COMMIT_REF_NAME" | perl -n -e '/^develop-\d[\d.]+-(.+)$/ and print ".".$1' ; )
        - cd rpm && COMPRESS=1 ./build.sh
    artifacts:
        paths:
            - rpm/RPMS/*.rpm

# Deploy RPMs to ubidev04 or some such
rpm-push:develop:
    # This image is maintaned in abms/docker-abms-devel project in GitLab and is a
    # minimal CentOS 7 image with tools required for creating and deploying RPM packages
    image: docker-reg.idscorporation.ca/abms/centos-builder:generic
    stage: rpm-push
    only:
        - /^develop(-.*)?$/
    script:
        # This will deploy the RPMs to a directory on ubidev04 that matches the name of the branch,
        # such as "develop" or "develop-1.2"
        deploy_rpms.sh rpm/RPMS/*.rpm

