export enum EditableType {
  FLIGHT_MOVEMENT = <any>'FLIGHT_MOVEMENT',
  INVOICE = <any>'INVOICE',
  LINE_ITEM = <any>'LINE_ITEM',
  TRANSACTION = <any>'TRANSACTION',
  TRANSACTION_PAYMENT = <any>'TRANSACTION_PAYMENT'
}
