
-- 01 ====  WAYPOINT insertion  =====================================================================================================================

-- 02 ====  'UL776' AIRWAY update  ====  Source: ATFM SYSTEM CUSTOMIZATIONS AF.pdf  =================================================================

-- 03 ====  'UL452' AIRWAY insertion  ====  Source: ATFM SYSTEM CUSTOMIZATIONS AF.pdf  ==============================================================

-- 04 ====  'UL462' AIRWAY update  ====  Source: ATFM SYSTEM CUSTOMIZATIONS AF.pdf  =================================================================

-- 05 ====  'UL576' AIRWAY insertion  ====  Source: ATFM SYSTEM CUSTOMIZATIONS AF.pdf  ==============================================================

-- 06 ====  'UB540' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 75781  =======================================================

-- 07 ====  'G653' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 75860  ========================================================

-- 08 ====  'UA409' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 75861  =======================================================

-- 09 ====  'UM214' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 75844  =======================================================

-- 10 ====  'UM315' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 91182  =======================================================

-- 11 ====  'UP312' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 91182  =======================================================

-- 12 ====  ADHP insertion  ====  Source: ICAO ICARD 5LNC  ====  Comment: Story 70290  ==============================================================

-- 13 ====  'UT916' AIRWAY update  ====  Source: ICAO ICARD 5LNC  ====  Comment: Nov. 09, 2017  =====================================================

-- 14 ====  ADHP insertion  ====  Source: WIKIPEDIA  ====  Comment: TFS 94885  ======================================================================

-- 15 ====  ADHP insertion  ====  Source: WIKIPEDIA  ====  Comment: TFS 94884  ======================================================================

-- 16 ====  ADHP insertion  ====  Source: WIKIPEDIA  ====  Comment: Observed by k.gubbins while analyzing KCAA data  ================================
update airport set validto = '2018-10-24T00:00:00'::timestamp without time zone where ident = 'HC0006';

-- 17 ====  ADHP insertion  ====  Source: WIKIPEDIA  ====  Comment: Observed by d.panech while analyzing KCAA data  =================================

-- 18 ====  WAYPOINT insertion  ====  Source: j.nicolaas@dc-ansp.org  ====  Comment: see also misc_docs/2018-09-26--curacao-waypoint/  ==============

-- 19 ====  ADHP insertion  ====  Source: w.reiche@idscorporation.com  ====  Comment: see also TFS 101774  ==========================================
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('27.34666633605957', '-26.366666793823242'), 4326), '27.34666633605957','-26.366666793823242','FACR','CARLTONVILLE','idsna','ourairports.com','FACR','WGE','5000.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('28.246', '-26.1392'), 4326), '28.246','-26.1392','FAJS','OR TAMBO INTERNATIONAL','idsna','ourairports.com','FAJS','WGE','5558.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('24.299999237060547', '-33.96666717529297'), 4326), '24.299999237060547','-33.96666717529297','FAKW','KAREEDOUW','idsna','ourairports.com','FAKW','WGE','1050.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('12.616999626159668', '-3.316999912261963'), 4326), '12.616999626159668','-3.316999912261963','FCMK','KELE KIBANGOU','idsna','ourairports.com','FCMK','WGE','902.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('12.866999626159668', '-3.1670000553131104'), 4326), '12.866999626159668','-3.1670000553131104','FCMZ','N''ZABI','idsna','ourairports.com','FCMZ','WGE','1640.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('28.4526004791', '-15.3308000565'), 4326), '28.4526004791','-15.3308000565','FLLS','KENNETH KAUNDA INTERNATIONAL AIRPORT LUSAKA','idsna','ourairports.com','FLLS','WGE','3779.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('28.66489982605', '-12.998100280762'), 4326), '28.66489982605','-12.998100280762','FLND','SIMON MWANSA KAPWEPWE INTERNATIONAL','idsna','ourairports.com','FLND','WGE','4167.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('19.12055', '-25.937782'), 4326), '19.12055','-25.937782','FYKS','KOES','idsna','ourairports.com','FYKS','WGE','3175.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('16.933000564575195', '-3.0'), 4326), '16.933000564575195','-3.0','FZBJ','MUSHIE','idsna','ourairports.com','FZBJ','WGE','1214.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('39.0059', '8.7163'), 4326), '39.0059','8.7163','HAHM','HARAR MEDA','idsna','ourairports.com','HAHM','WGE','6201.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('46.6375', '6.095833'), 4326), '46.6375','6.095833','HCAD','ADADO','idsna',NULL,'HCAD','WGE','1001.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('46.193889', '6.180278'), 4326), '46.193889','6.180278','HCAW','ABUDWAQ','idsna',NULL,'HCAW','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('45.566667', '3.85'), 4326), '45.566667','3.85','HCBB','BULE BURDE','idsna',NULL,'HCBB','WGE',NULL,'FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('49.9085', '11.494'), 4326), '49.9085','11.494','HCMC','CANDALA','idsna','ourairports.com','HCMC','WGE','30.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('48.516666412353516', '5.366666793823242'), 4326), '48.516666412353516','5.366666793823242','HCMO','OBBIA','idsna','ourairports.com','HCMO','WGE','65.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('48.567407', '8.457942'), 4326), '48.567407','8.457942','HCMW','GAROWE','idsna','ourairports.com','HCMW','WGE','1465.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('37.04100799560547', '-0.06239889934659004'), 4326), '37.04100799560547','-0.06239889934659004','HKNY','NANYUKI','idsna','ourairports.com','HKNY','WGE','6250.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('34.78300094604492', '0.6169999837875366'), 4326), '34.78300094604492','0.6169999837875366','HKWE','WEBUYE','idsna','ourairports.com','HKWE','WGE','4300.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.600485', '6.195865'), 4326), '31.600485','6.195865','HSBR','BOR','idsna','ourairports.com','HSBR','WGE','1394.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('33.58300018310547', '4.7829999923706055'), 4326), '33.58300018310547','4.7829999923706055','HSKP','KAPOETA','idsna','ourairports.com','HSKP','WGE','2220.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('31.8185', '18.455'), 4326), '31.8185','18.455','HSMR','MEROWE','idsna','ourairports.com','HSMR','WGE','864.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('30.7280731201', '4.13028160099'), 4326), '30.7280731201','4.13028160099','HSYE','YEI','idsna','ourairports.com','HSYE','WGE','2000.0','FT') RETURNING "airport_pk";
INSERT INTO navdb.airport (airport_pk, effectivedt, updatedt, validfrom, validto, bltype, geom, longitude, latitude, ident, nam, updateoper, source, codeicao, codedatum, elevation, p_geoiduom) VALUES ((SELECT MAX(airport_pk) + 1 FROM navdb.airport), current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, current_timestamp::timestamp without time zone, 'infinity'::timestamp without time zone, 'A', ST_SetSRID(ST_MakePoint('35.012298584', '31.208299636799996'), 4326), '35.012298584','31.208299636799996','LLNV','NEVATIM AIR BASE','idsna','ourairports.com','LLNV','WGE','1330.0','FT') RETURNING "airport_pk";
