--------------------------------------------------------------------
-- DO NOT ADD TO MIGRATION CHANGELOG, THIS WILL BE RUN MANUALLY!! --
--------------------------------------------------------------------

-- NOTE: account IDs and external charge category names must exists

-- insert account external charge categories for CAAB Sage
INSERT INTO account_external_charge_categories (account_id, external_charge_category_id, external_system_identifier) VALUES

    -------------------
    -- IATA Accounts --
    -------------------
    (108, external_charge_category_id('IATA'), 'IAI005'),
    (6, external_charge_category_id('IATA'), 'IAI001'),
    (107, external_charge_category_id('IATA'), 'IAI004'),
    (15, external_charge_category_id('IATA'), 'IAI002'),
    (23, external_charge_category_id('IATA'), 'IAI003'),
    (88, external_charge_category_id('IATA'), 'ISA005'),
    (24, external_charge_category_id('IATA'), 'IAR001'),
    (56, external_charge_category_id('IATA'), 'IVE001'),
    (79, external_charge_category_id('IATA'), 'IAW002'),
    (10, external_charge_category_id('IATA'), 'IBR001'),
    (25, external_charge_category_id('IATA'), 'IBR002'),
    (27, external_charge_category_id('IATA'), 'ICA002'),
    (109, external_charge_category_id('IATA'), 'ICA003'),
    (26, external_charge_category_id('IATA'), 'ICA001'),
    (205, external_charge_category_id('IATA'), 'ICEM001'),
    (28, external_charge_category_id('IATA'), 'ICO002'),
    (30, external_charge_category_id('IATA'), 'IDE003'),
    (33, external_charge_category_id('IATA'), 'IEL001'),
    (31, external_charge_category_id('IATA'), 'IET001'),
    (111, external_charge_category_id('IATA'), 'IETIH001'),
    (32, external_charge_category_id('IATA'), 'IFL001'),
    (34, external_charge_category_id('IATA'), 'IGR001'),
    (35, external_charge_category_id('IATA'), 'IIB001'),
    (36, external_charge_category_id('IATA'), 'IJO001'),
    (37, external_charge_category_id('IATA'), 'IKE001'),
    (80, external_charge_category_id('IATA'), 'ILATA001'),
    (29, external_charge_category_id('IATA'), 'IDE002'),
    (38, external_charge_category_id('IATA'), 'ILU001'),
    (87, external_charge_category_id('IATA'), 'IMA002'),
    (39, external_charge_category_id('IATA'), 'IOM001'),
    (17, external_charge_category_id('IATA'), 'IQA001'),
    (40, external_charge_category_id('IATA'), 'IRO001'),
    (101, external_charge_category_id('IATA'), 'IUN001'),
    (41, external_charge_category_id('IATA'), 'IRW001'),
    (447, external_charge_category_id('IATA'), 'ISA005'),
    (44, external_charge_category_id('IATA'), 'ISA004'),
    (16, external_charge_category_id('IATA'), 'ISA005'),
    (42, external_charge_category_id('IATA'), 'ISA001'),
    (50, external_charge_category_id('IATA'), 'ISA002'),
    (43, external_charge_category_id('IATA'), 'ISW003'),
    (53, external_charge_category_id('IATA'), 'ITA003'),
    (45, external_charge_category_id('IATA'), 'ITA002'),
    (46, external_charge_category_id('IATA'), 'ITU001'),
    (48, external_charge_category_id('IATA'), 'IVI001'),
    (49, external_charge_category_id('IATA'), 'IVI002'),
    (213, external_charge_category_id('IATA'), 'IZA003'),

    ----------------------
    -- ENROUTE Accounts --
    ----------------------
    (75, external_charge_category_id('ENROUTE'), 'YAB003'),
    (337, external_charge_category_id('ENROUTE'), 'YAB001'),
    (354, external_charge_category_id('ENROUTE'), 'YAB004'),
    (387, external_charge_category_id('ENROUTE'), 'YAC003'),
    (175, external_charge_category_id('ENROUTE'), 'YAER002'),
    (82, external_charge_category_id('ENROUTE'), 'YAIRA001'),
    (181, external_charge_category_id('ENROUTE'), 'YAI009'),
    (204, external_charge_category_id('ENROUTE'), 'YAR2001'),
    (179, external_charge_category_id('ENROUTE'), 'YAM001'),
    (375, external_charge_category_id('ENROUTE'), 'YAR002'),
    (536, external_charge_category_id('ENROUTE'), 'YAU003'),
    (56, external_charge_category_id('ENROUTE'), 'YAVE001'),
    (266, external_charge_category_id('ENROUTE'), 'YAV006'),
    (540, external_charge_category_id('ENROUTE'), 'YAV006'),
    (79, external_charge_category_id('ENROUTE'), 'YAW001'),
    (81, external_charge_category_id('ENROUTE'), 'YBA002'),
    (185, external_charge_category_id('ENROUTE'), 'YBES001'),
    (174, external_charge_category_id('ENROUTE'), 'YBR002'),
    (94, external_charge_category_id('ENROUTE'), 'YCA010'),
    (203, external_charge_category_id('ENROUTE'), 'YCO007'),
    (205, external_charge_category_id('ENROUTE'), 'YCE003'),
    (269, external_charge_category_id('ENROUTE'), 'YCHO001'),
    (55, external_charge_category_id('ENROUTE'), 'YCO001'),
    (537, external_charge_category_id('ENROUTE'), 'YCO008'),
    (558, external_charge_category_id('ENROUTE'), 'YCOR001'),
    (198, external_charge_category_id('ENROUTE'), 'YDE005'),
    (188, external_charge_category_id('ENROUTE'), 'YDE007'),
    (59, external_charge_category_id('ENROUTE'), 'YSO006'),
    (183, external_charge_category_id('ENROUTE'), 'YECO001'),
    (78, external_charge_category_id('ENROUTE'), 'YEMP001'),
    (195, external_charge_category_id('ENROUTE'), 'YEND001'),
    (538, external_charge_category_id('ENROUTE'), 'YEQU001'),
    (77, external_charge_category_id('ENROUTE'), 'YEX004'),
    (262, external_charge_category_id('ENROUTE'), 'YEX004'),
    (539, external_charge_category_id('ENROUTE'), 'YEX008'),
    (210, external_charge_category_id('ENROUTE'), 'YFA002'),
    (86, external_charge_category_id('ENROUTE'), 'YFSJ001'),
    (54, external_charge_category_id('ENROUTE'), 'YFE001'),
    (58, external_charge_category_id('ENROUTE'), 'YJE008'),
    (32, external_charge_category_id('ENROUTE'), 'YFLY001'),
    (155, external_charge_category_id('ENROUTE'), 'GKN001'),
    (583, external_charge_category_id('ENROUTE'), 'YGE004'),
    (339, external_charge_category_id('ENROUTE'), 'YGL002'),
    (259, external_charge_category_id('ENROUTE'), 'YEQ001'),
    (260, external_charge_category_id('ENROUTE'), 'YZAMB001'),
    (255, external_charge_category_id('ENROUTE'), 'YGU001'),
    (104, external_charge_category_id('ENROUTE'), 'YHALST001'),
    (173, external_charge_category_id('ENROUTE'), 'YHEL001'),
    (257, external_charge_category_id('ENROUTE'), 'YIN003'),
    (57, external_charge_category_id('ENROUTE'), 'YJE007'),
    (517, external_charge_category_id('ENROUTE'), 'YJE004'),
    (518, external_charge_category_id('ENROUTE'), 'YKI001'),
    (342, external_charge_category_id('ENROUTE'), 'YKI004'),
    (336, external_charge_category_id('ENROUTE'), 'YMA004'),
    (153, external_charge_category_id('ENROUTE'), 'YMO003'),
    (209, external_charge_category_id('ENROUTE'), 'YMS001'),
    (191, external_charge_category_id('ENROUTE'), 'YNA007'),
    (152, external_charge_category_id('ENROUTE'), 'YNGW001'),
    (546, external_charge_category_id('ENROUTE'), 'YRAU001'),
    (101, external_charge_category_id('ENROUTE'), 'YRO002'),
    (105, external_charge_category_id('ENROUTE'), 'YSA012'),
    (261, external_charge_category_id('ENROUTE'), 'YSA011'),
    (212, external_charge_category_id('ENROUTE'), 'YSC001'),
    (439, external_charge_category_id('ENROUTE'), 'SHR001'),
    (516, external_charge_category_id('ENROUTE'), 'YSK005'),
    (201, external_charge_category_id('ENROUTE'), 'YSK001'),
    (76, external_charge_category_id('ENROUTE'), 'YSO006'),
    (102, external_charge_category_id('ENROUTE'), 'YSOA001'),
    (16, external_charge_category_id('ENROUTE'), 'YSA007'),
    (356, external_charge_category_id('ENROUTE'), 'YSAB01'),
    (250, external_charge_category_id('ENROUTE'), 'YSAP001'),
    (343, external_charge_category_id('ENROUTE'), 'YSO001'),
    (4, external_charge_category_id('ENROUTE'), 'YST005'),
    (519, external_charge_category_id('ENROUTE'), 'CASH01'),
    (186, external_charge_category_id('ENROUTE'), 'CASH01'),
    (112, external_charge_category_id('ENROUTE'), 'CASH01'),
    (208, external_charge_category_id('ENROUTE'), 'YSW003'),
    (13, external_charge_category_id('ENROUTE'), 'YTA002'),
    (106, external_charge_category_id('ENROUTE'), 'YTR001'),
    (114, external_charge_category_id('ENROUTE'), 'CASH01'),
    (207, external_charge_category_id('ENROUTE'), 'YTEI001'),
    (357, external_charge_category_id('ENROUTE'), 'YTEN001'),
    (177, external_charge_category_id('ENROUTE'), 'YTETRA001'),
    (184, external_charge_category_id('ENROUTE'), 'YTIT001'),
    (189, external_charge_category_id('ENROUTE'), 'YTR008'),
    (440, external_charge_category_id('ENROUTE'), 'YUN004'),
    (95, external_charge_category_id('ENROUTE'), 'YUNIQ001'),
    (151, external_charge_category_id('ENROUTE'), 'YUNI002'),
    (150, external_charge_category_id('ENROUTE'), 'YVI003'),
    (318, external_charge_category_id('ENROUTE'), 'YWBH001'),
    (52, external_charge_category_id('ENROUTE'), 'YWE005'),
    (338, external_charge_category_id('ENROUTE'), 'YWE007'),
    (8, external_charge_category_id('ENROUTE'), 'YSE002'),
    (73, external_charge_category_id('ENROUTE'), 'YWO002'),

    ---------------------------
    -- AERONAUTICAL Accounts --
    ---------------------------
    (395, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (103, external_charge_category_id('AERONAUTICAL'), 'AFR001'),
    (72, external_charge_category_id('AERONAUTICAL'), 'AFR010'),
    (340, external_charge_category_id('AERONAUTICAL'), 'AFR016'),
    (392, external_charge_category_id('AERONAUTICAL'), 'AFR002'),
    (6, external_charge_category_id('AERONAUTICAL'), 'AIR025'),
    (561, external_charge_category_id('AERONAUTICAL'), 'AIR025'),
    (510, external_charge_category_id('AERONAUTICAL'), 'AIR025'),
    (107, external_charge_category_id('AERONAUTICAL'), 'YAI013'),
    (14, external_charge_category_id('AERONAUTICAL'), 'AIRF001'),
    (15, external_charge_category_id('AERONAUTICAL'), 'NAM002'),
    (156, external_charge_category_id('AERONAUTICAL'), 'AIR041'),
    (66, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (88, external_charge_category_id('AERONAUTICAL'), 'SAA007'),
    (367, external_charge_category_id('AERONAUTICAL'), 'HAA002'),
    (393, external_charge_category_id('AERONAUTICAL'), 'ALI003'),
    (3, external_charge_category_id('AERONAUTICAL'), 'IAL001'),
    (352, external_charge_category_id('AERONAUTICAL'), 'ARI002'),
    (193, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (376, external_charge_category_id('AERONAUTICAL'), 'AVI012'),
    (283, external_charge_category_id('AERONAUTICAL'), 'AVT001'),
    (167, external_charge_category_id('AERONAUTICAL'), 'BRET002'),
    (100, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (196, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (391, external_charge_category_id('AERONAUTICAL'), 'BORO001'),
    (194, external_charge_category_id('AERONAUTICAL'), 'BOT004'),
    (71, external_charge_category_id('AERONAUTICAL'), 'BDF001'),
    (171, external_charge_category_id('AERONAUTICAL'), 'SABO001'),
    (170, external_charge_category_id('AERONAUTICAL'), 'BOT012'),
    (299, external_charge_category_id('AERONAUTICAL'), 'BTO001'),
    (522, external_charge_category_id('AERONAUTICAL'), 'BRI005'),
    (10, external_charge_category_id('AERONAUTICAL'), 'BRI001'),
    (554, external_charge_category_id('AERONAUTICAL'), 'BUS001'),
    (187, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (378, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (348, external_charge_category_id('AERONAUTICAL'), 'CAR001'),
    (70, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (281, external_charge_category_id('AERONAUTICAL'), 'RECA001'),
    (83, external_charge_category_id('AERONAUTICAL'), 'CAT003'),
    (97, external_charge_category_id('AERONAUTICAL'), 'CHO005'),
    (18, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (559, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (91, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (344, external_charge_category_id('AERONAUTICAL'), 'CONN001'),
    (515, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (206, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (298, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (577, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (563, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (560, external_charge_category_id('AERONAUTICAL'), 'DAN009'),
    (514, external_charge_category_id('AERONAUTICAL'), 'DAV004'),
    (492, external_charge_category_id('AERONAUTICAL'), 'DAV002'),
    (569, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (166, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (165, external_charge_category_id('AERONAUTICAL'), 'DEW001'),
    (158, external_charge_category_id('AERONAUTICAL'), 'DEB003'),
    (149, external_charge_category_id('AERONAUTICAL'), 'DEL002'),
    (426, external_charge_category_id('AERONAUTICAL'), 'DER002'),
    (188, external_charge_category_id('AERONAUTICAL'), 'DES005'),
    (282, external_charge_category_id('AERONAUTICAL'), 'DIR002'),
    (297, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (501, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (438, external_charge_category_id('AERONAUTICAL'), 'MIK001'),
    (47, external_charge_category_id('AERONAUTICAL'), 'EMI002'),
    (31, external_charge_category_id('AERONAUTICAL'), 'ETH001'),
    (180, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (562, external_charge_category_id('AERONAUTICAL'), 'EXE003'),
    (347, external_charge_category_id('AERONAUTICAL'), 'MEA001'),
    (164, external_charge_category_id('AERONAUTICAL'), 'FEE001'),
    (317, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (157, external_charge_category_id('AERONAUTICAL'), 'FLY006'),
    (566, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (567, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (573, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (379, external_charge_category_id('AERONAUTICAL'), 'IDG4001'),
    (200, external_charge_category_id('AERONAUTICAL'), 'GAB003'),
    (389, external_charge_category_id('AERONAUTICAL'), 'GBUC01'),
    (251, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (585, external_charge_category_id('AERONAUTICAL'), 'GEO004'),
    (542, external_charge_category_id('AERONAUTICAL'), 'ZUT001'),
    (89, external_charge_category_id('AERONAUTICAL'), 'RHU001'),
    (60, external_charge_category_id('AERONAUTICAL'), 'AIR030'),
    (588, external_charge_category_id('AERONAUTICAL'), 'CAR009'),
    (572, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (168, external_charge_category_id('AERONAUTICAL'), 'HEL002'),
    (346, external_charge_category_id('AERONAUTICAL'), 'HOT001'),
    (84, external_charge_category_id('AERONAUTICAL'), 'AVA001'),
    (178, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (565, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (571, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (581, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (578, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (57, external_charge_category_id('AERONAUTICAL'), 'JEM002'),
    (580, external_charge_category_id('AERONAUTICAL'), 'PRI004'),
    (154, external_charge_category_id('AERONAUTICAL'), 'JOH004'),
    (579, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (584, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (555, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (564, external_charge_category_id('AERONAUTICAL'), 'JSB001'),
    (113, external_charge_category_id('AERONAUTICAL'), 'AIR028'),
    (293, external_charge_category_id('AERONAUTICAL'), 'KAL003'),
    (159, external_charge_category_id('AERONAUTICAL'), 'KAV003'),
    (37, external_charge_category_id('AERONAUTICAL'), 'KEN001'),
    (543, external_charge_category_id('AERONAUTICAL'), 'KIN006'),
    (90, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (110, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (425, external_charge_category_id('AERONAUTICAL'), 'AELI001'),
    (377, external_charge_category_id('AERONAUTICAL'), 'LOG001'),
    (576, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (7, external_charge_category_id('AERONAUTICAL'), 'MAC002'),
    (93, external_charge_category_id('AERONAUTICAL'), 'MAJ003'),
    (74, external_charge_category_id('AERONAUTICAL'), 'MAN001'),
    (162, external_charge_category_id('AERONAUTICAL'), 'MAC006'),
    (452, external_charge_category_id('AERONAUTICAL'), 'MASC001'),
    (284, external_charge_category_id('AERONAUTICAL'), 'MOC002'),
    (99, external_charge_category_id('AERONAUTICAL'), 'MCC001'),
    (69, external_charge_category_id('AERONAUTICAL'), 'MOR003'),
    (330, external_charge_category_id('AERONAUTICAL'), 'MOS002'),
    (285, external_charge_category_id('AERONAUTICAL'), 'MOT001'),
    (153, external_charge_category_id('AERONAUTICAL'), 'MOT002'),
    (349, external_charge_category_id('AERONAUTICAL'), 'APJ001'),
    (547, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (190, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (254, external_charge_category_id('AERONAUTICAL'), 'NAC006'),
    (553, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (586, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (211, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (556, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (92, external_charge_category_id('AERONAUTICAL'), 'OWE001'),
    (192, external_charge_category_id('AERONAUTICAL'), 'CASH 01'),
    (331, external_charge_category_id('AERONAUTICAL'), 'CASH 01'),
    (353, external_charge_category_id('AERONAUTICAL'), 'PHAR001'),
    (85, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (557, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (582, external_charge_category_id('AERONAUTICAL'), 'RAD001'),
    (270, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (390, external_charge_category_id('AERONAUTICAL'), 'RHIN003'),
    (574, external_charge_category_id('AERONAUTICAL'), 'GAS004'),
    (161, external_charge_category_id('AERONAUTICAL'), 'CASH 01'),
    (568, external_charge_category_id('AERONAUTICAL'), 'CASH 01'),
    (51, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (105, external_charge_category_id('AERONAUTICAL'), 'SAF003'),
    (160, external_charge_category_id('AERONAUTICAL'), 'XUG001'),
    (96, external_charge_category_id('AERONAUTICAL'), 'CASH 01'),
    (351, external_charge_category_id('AERONAUTICAL'), 'AISC001'),
    (350, external_charge_category_id('AERONAUTICAL'), 'SCRE001'),
    (286, external_charge_category_id('AERONAUTICAL'), 'SEN001'),
    (439, external_charge_category_id('AERONAUTICAL'), 'BRE002'),
    (197, external_charge_category_id('AERONAUTICAL'), 'CASH 01'),
    (16, external_charge_category_id('AERONAUTICAL'), 'SAA007'),
    (50, external_charge_category_id('AERONAUTICAL'), 'COM008'),
    (258, external_charge_category_id('AERONAUTICAL'), 'CASH 01'),
    (332, external_charge_category_id('AERONAUTICAL'), 'SSG001'),
    (548, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (4, external_charge_category_id('AERONAUTICAL'), 'STA002'),
    (169, external_charge_category_id('AERONAUTICAL'), 'STA006'),
    (373, external_charge_category_id('AERONAUTICAL'), 'TES001'),
    (520, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (248, external_charge_category_id('AERONAUTICAL'), 'CASH01'),
    (184, external_charge_category_id('AERONAUTICAL'), 'TIT002'),
    (545, external_charge_category_id('AERONAUTICAL'), 'TRO010'),
    (289, external_charge_category_id('AERONAUTICAL'), 'TSE002'),
    (570, external_charge_category_id('AERONAUTICAL'), 'CASH 01'),
    (440, external_charge_category_id('AERONAUTICAL'), 'UNI012'),
    (98, external_charge_category_id('AERONAUTICAL'), 'CASH 01'),
    (541, external_charge_category_id('AERONAUTICAL'), 'CASH 01'),
    (355, external_charge_category_id('AERONAUTICAL'), 'CASH 01'),
    (256, external_charge_category_id('AERONAUTICAL'), 'CASH 01'),
    (291, external_charge_category_id('AERONAUTICAL'), 'WIL021'),
    (8, external_charge_category_id('AERONAUTICAL'), 'SEF003'),
    (512, external_charge_category_id('AERONAUTICAL'), 'SEF003'),
    (441, external_charge_category_id('AERONAUTICAL'), 'SEF009'),
    (493, external_charge_category_id('AERONAUTICAL'), 'SEF003'),
    (302, external_charge_category_id('AERONAUTICAL'), 'WOR002'),
    (176, external_charge_category_id('AERONAUTICAL'), 'EXC002'),

    ------------------------
    -- TELEPHONE Accounts --
    ------------------------
    (88, external_charge_category_id('TELEPHONE'), 'UTSAA001'),
    (400, external_charge_category_id('TELEPHONE'), 'TEDINFBFT001'),
    (172, external_charge_category_id('TELEPHONE'), 'CASH01'),
    (467, external_charge_category_id('TELEPHONE'), 'CASH01'),
    (313, external_charge_category_id('TELEPHONE'), 'KOP001'),
    (413, external_charge_category_id('TELEPHONE'), 'TEKU001'),
    (487, external_charge_category_id('TELEPHONE'), 'TEMATFBSK001'),
    (477, external_charge_category_id('TELEPHONE'), 'MOD002'),
    (409, external_charge_category_id('TELEPHONE'), 'MOI001'),
    (312, external_charge_category_id('TELEPHONE'), 'TELEFBSK 001'),
    (330, external_charge_category_id('TELEPHONE'), 'TEMO007'),
    (252, external_charge_category_id('TELEPHONE'), 'GAE001'),
    (341, external_charge_category_id('TELEPHONE'), 'NNY0001'),
    (470, external_charge_category_id('TELEPHONE'), 'TEPELFBKE001'),
    (398, external_charge_category_id('TELEPHONE'), 'TEOG001'),
    (310, external_charge_category_id('TELEPHONE'), 'TEON002'),
    (329, external_charge_category_id('TELEPHONE'), 'TEOAFBSK 001'),
    (319, external_charge_category_id('TELEPHONE'), 'ONT002'),
    (411, external_charge_category_id('TELEPHONE'), 'TEFO001'),
    (207, external_charge_category_id('TELEPHONE'), 'TEI002'),
    (177, external_charge_category_id('TELEPHONE'), 'TET001'),
    (491, external_charge_category_id('TELEPHONE'), 'TII001'),
    (402, external_charge_category_id('TELEPHONE'), 'TELMA FT001'),

    --------------------------
    -- ELECTRICITY Accounts --
    --------------------------
    (531, external_charge_category_id('ELECTRICITY'), 'ELAJEW&C001'),
    (401, external_charge_category_id('ELECTRICITY'), 'ELAGFT001'),
    (524, external_charge_category_id('ELECTRICITY'), 'UTAB001'),
    (15, external_charge_category_id('ELECTRICITY'), 'ELAIRFBSK001'),
    (308, external_charge_category_id('ELECTRICITY'), 'ELAGHFBSK001'),
    (88, external_charge_category_id('ELECTRICITY'), 'UTSAA001'),
    (526, external_charge_category_id('ELECTRICITY'), 'ELALFBMN001'),
    (397, external_charge_category_id('ELECTRICITY'), 'ELALFT001'),
    (527, external_charge_category_id('ELECTRICITY'), 'ELATFBMN001'),
    (273, external_charge_category_id('ELECTRICITY'), 'ELATFBSK 001'),
    (359, external_charge_category_id('ELECTRICITY'), 'ELATFBFT001'),
    (424, external_charge_category_id('ELECTRICITY'), 'ELAV FT001'),
    (528, external_charge_category_id('ELECTRICITY'), 'ELAV FT001'),
    (265, external_charge_category_id('ELECTRICITY'), 'ELAVFBSK 001'),
    (364, external_charge_category_id('ELECTRICITY'), 'ELBU FT001'),
    (280, external_charge_category_id('ELECTRICITY'), 'ELBUFBSK 001'),
    (406, external_charge_category_id('ELECTRICITY'), 'ELNTFT001'),
    (268, external_charge_category_id('ELECTRICITY'), 'ELBOIFBSK001'),
    (414, external_charge_category_id('ELECTRICITY'), 'ELRAFT001'),
    (407, external_charge_category_id('ELECTRICITY'), 'ELBOFT001'),
    (272, external_charge_category_id('ELECTRICITY'), 'ELBOFBSK 001'),
    (365, external_charge_category_id('ELECTRICITY'), 'ELPOFBFT001'),
    (529, external_charge_category_id('ELECTRICITY'), 'ELBUFBMN001'),
    (314, external_charge_category_id('ELECTRICITY'), 'ELSOFBSK 002'),
    (371, external_charge_category_id('ELECTRICITY'), 'ELBUFT001'),
    (412, external_charge_category_id('ELECTRICITY'), 'ELBUFT001'),
    (400, external_charge_category_id('ELECTRICITY'), 'ELDIFT001'),
    (410, external_charge_category_id('ELECTRICITY'), 'ELFTEL001'),
    (31, external_charge_category_id('ELECTRICITY'), 'ELETFBSK001'),
    (277, external_charge_category_id('ELECTRICITY'), 'ELEUFBSK 001'),
    (361, external_charge_category_id('ELECTRICITY'), 'ELEUFBFT 001'),
    (157, external_charge_category_id('ELECTRICITY'), 'ELFLFBSK 001'),
    (368, external_charge_category_id('ELECTRICITY'), 'ELGAFT001'),
    (316, external_charge_category_id('ELECTRICITY'), 'ELMHFBSK 001'),
    (399, external_charge_category_id('ELECTRICITY'), 'ELGEFT001'),
    (417, external_charge_category_id('ELECTRICITY'), 'ELKUFT001'),
    (323, external_charge_category_id('ELECTRICITY'), 'ELNGFBSK 001'),
    (408, external_charge_category_id('ELECTRICITY'), 'ELGLFBFT 001'),
    (320, external_charge_category_id('ELECTRICITY'), 'ELPUFBSK 001'),
    (288, external_charge_category_id('ELECTRICITY'), 'ELGRFBSK 001'),
    (168, external_charge_category_id('ELECTRICITY'), 'ELHE001'),
    (278, external_charge_category_id('ELECTRICITY'), 'ELHE001'),
    (84, external_charge_category_id('ELECTRICITY'), 'ELIASFBSK001'),
    (328, external_charge_category_id('ELECTRICITY'), 'ELISFBSK 001'),
    (403, external_charge_category_id('ELECTRICITY'), 'ELJOFT001'),
    (550, external_charge_category_id('ELECTRICITY'), 'ELJMFT001'),
    (324, external_charge_category_id('ELECTRICITY'), 'ELJOFBSK 001'),
    (311, external_charge_category_id('ELECTRICITY'), 'ELKMFBSK 001'),
    (113, external_charge_category_id('ELECTRICITY'), 'ELKAFBSK 001'),
    (293, external_charge_category_id('ELECTRICITY'), 'ELKFFBSK 002'),
    (326, external_charge_category_id('ELECTRICITY'), 'ELKSFBSK001'),
    (532, external_charge_category_id('ELECTRICITY'), 'ELKAVFBMN001'),
    (549, external_charge_category_id('ELECTRICITY'), 'ELDITFBFT001'),
    (372, external_charge_category_id('ELECTRICITY'), 'ELDITFBFT001'),
    (37, external_charge_category_id('ELECTRICITY'), 'ELKEFBSK001'),
    (313, external_charge_category_id('ELECTRICITY'), 'ELKOFBSK001'),
    (413, external_charge_category_id('ELECTRICITY'), 'ELKU001'),
    (374, external_charge_category_id('ELECTRICITY'), 'ELLEFT001'),
    (396, external_charge_category_id('ELECTRICITY'), 'ELLEFT001'),
    (93, external_charge_category_id('ELECTRICITY'), 'ELAMAJFBSK00'),
    (452, external_charge_category_id('ELECTRICITY'), 'ELMASFBSK001'),
    (322, external_charge_category_id('ELECTRICITY'), 'ELNTFBSK 001'),
    (404, external_charge_category_id('ELECTRICITY'), 'ELMIFBFT001'),
    (409, external_charge_category_id('ELECTRICITY'), 'ELRADFBFT001'),
    (312, external_charge_category_id('ELECTRICITY'), 'ELLEFBSK 001'),
    (533, external_charge_category_id('ELECTRICITY'), 'ELMO001'),
    (369, external_charge_category_id('ELECTRICITY'), 'ELMMFBFT001'),
    (285, external_charge_category_id('ELECTRICITY'), 'ELMTFBSK001'),
    (405, external_charge_category_id('ELECTRICITY'), 'ELMPFBFT001'),
    (252, external_charge_category_id('ELECTRICITY'), 'ELGMFBSK 001'),
    (427, external_charge_category_id('ELECTRICITY'), 'ELMRIFBSK001'),
    (305, external_charge_category_id('ELECTRICITY'), 'ELMUGFBSK001'),
    (341, external_charge_category_id('ELECTRICITY'), 'ELMOFBSK002'),
    (315, external_charge_category_id('ELECTRICITY'), 'ELBAFBSK001'),
    (398, external_charge_category_id('ELECTRICITY'), 'ELOGFT001'),
    (534, external_charge_category_id('ELECTRICITY'), 'ELOARFBMN001'),
    (575, external_charge_category_id('ELECTRICITY'), 'ELOARFBMN001'),
    (506, external_charge_category_id('ELECTRICITY'), 'ELOARFBMN001'),
    (310, external_charge_category_id('ELECTRICITY'), 'ELOMFBSK 001'),
    (329, external_charge_category_id('ELECTRICITY'), 'ELALFBSK 001'),
    (319, external_charge_category_id('ELECTRICITY'), 'ELONFBSK 001'),
    (411, external_charge_category_id('ELECTRICITY'), 'ELONFBFT002'),
    (418, external_charge_category_id('ELECTRICITY'), 'ELONFBFT001'),
    (530, external_charge_category_id('ELECTRICITY'), 'ELPOFBMN001'),
    (267, external_charge_category_id('ELECTRICITY'), 'ELBPFBSK 001'),
    (523, external_charge_category_id('ELECTRICITY'), 'ELPUMAFBMN01'),
    (419, external_charge_category_id('ELECTRICITY'), 'ELQUEFBFT001'),
    (327, external_charge_category_id('ELECTRICITY'), 'ELRTFBSK 001'),
    (300, external_charge_category_id('ELECTRICITY'), 'ELROLFBSK001'),
    (525, external_charge_category_id('ELECTRICITY'), 'ELSAFBSK001'),
    (495, external_charge_category_id('ELECTRICITY'), 'ELSAALFBMN01'),
    (16, external_charge_category_id('ELECTRICITY'), 'ELSAFBSK001'),
    (384, external_charge_category_id('ELECTRICITY'), 'ELSAALFBMN01'),
    (50, external_charge_category_id('ELECTRICITY'), 'ELSOFBSK 001'),
    (332, external_charge_category_id('ELECTRICITY'), 'ELSSGFBSK001'),
    (264, external_charge_category_id('ELECTRICITY'), 'ELTHFBSK 001'),
    (416, external_charge_category_id('ELECTRICITY'), 'ELSIFBFT001'),
    (321, external_charge_category_id('ELECTRICITY'), 'ELTSFBSK001'),
    (402, external_charge_category_id('ELECTRICITY'), 'ELVIFT001'),
    (302, external_charge_category_id('ELECTRICITY'), 'ELWFFBSK001'),

    --------------------
    -- WATER Accounts --
    --------------------
    (401, external_charge_category_id('WATER'), 'WAAGFT001'),
    (88, external_charge_category_id('WATER'), 'UTSAA001'),
    (397, external_charge_category_id('WATER'), 'WAALFT001'),
    (424, external_charge_category_id('WATER'), 'WA AVIS FT01'),
    (406, external_charge_category_id('WATER'), 'WANTFT001'),
    (486, external_charge_category_id('WATER'), 'WABBFBKE001'),
    (414, external_charge_category_id('WATER'), 'WARAFT001'),
    (407, external_charge_category_id('WATER'), 'WABOFT001'),
    (420, external_charge_category_id('WATER'), 'WAFTBDF001'),
    (314, external_charge_category_id('WATER'), 'WASOFBSK 001'),
    (371, external_charge_category_id('WATER'), 'ELBUFT001'),
    (412, external_charge_category_id('WATER'), 'WABUFT001'),
    (400, external_charge_category_id('WATER'), 'WADIFT001'),
    (410, external_charge_category_id('WATER'), 'WAFTEL001'),
    (361, external_charge_category_id('WATER'), 'WAEUFBFT 001'),
    (370, external_charge_category_id('WATER'), 'WAFRFT001'),
    (368, external_charge_category_id('WATER'), 'WAGAFT001'),
    (316, external_charge_category_id('WATER'), 'WAMHFBSK 001'),
    (399, external_charge_category_id('WATER'), 'WAGEFT001'),
    (417, external_charge_category_id('WATER'), 'WAKUFT001'),
    (408, external_charge_category_id('WATER'), 'WAGLFBFT 001'),
    (168, external_charge_category_id('WATER'), 'WAHE001'),
    (278, external_charge_category_id('WATER'), 'WAHE001'),
    (84, external_charge_category_id('WATER'), 'WAIASFBSK001'),
    (483, external_charge_category_id('WATER'), 'WAISFBKE001'),
    (328, external_charge_category_id('WATER'), 'WAISFBSK 001'),
    (415, external_charge_category_id('WATER'), 'WAUR FT001'),
    (403, external_charge_category_id('WATER'), 'WAJOFT001'),
    (550, external_charge_category_id('WATER'), 'WAJMFT001'),
    (488, external_charge_category_id('WATER'), 'WAJKFBKE001'),
    (311, external_charge_category_id('WATER'), 'WAKMFBSK 001'),
    (293, external_charge_category_id('WATER'), 'WAKFFBSK 001'),
    (326, external_charge_category_id('WATER'), 'WAKSFBSK001'),
    (372, external_charge_category_id('WATER'), 'WADITFBFT001'),
    (313, external_charge_category_id('WATER'), 'WAKOFBSK001'),
    (413, external_charge_category_id('WATER'), 'WAKUT001'),
    (374, external_charge_category_id('WATER'), 'WALEFT001'),
    (396, external_charge_category_id('WATER'), 'WALEFT001'),
    (93, external_charge_category_id('WATER'), 'WAMAJFBSK001'),
    (322, external_charge_category_id('WATER'), 'WANTFBSK 001'),
    (404, external_charge_category_id('WATER'), 'WAMIFBFT001'),
    (477, external_charge_category_id('WATER'), 'WAMSFBKE001'),
    (409, external_charge_category_id('WATER'), 'WARADFBFT001'),
    (312, external_charge_category_id('WATER'), 'WALEFBSK 001'),
    (481, external_charge_category_id('WATER'), 'WAMOFBKE001'),
    (476, external_charge_category_id('WATER'), 'WAMOKE001'),
    (533, external_charge_category_id('WATER'), 'ELMO001.'),
    (369, external_charge_category_id('WATER'), 'WAMMFBFT001'),
    (285, external_charge_category_id('WATER'), 'WAMTFBSK001'),
    (405, external_charge_category_id('WATER'), 'WAMPFBFT001'),
    (252, external_charge_category_id('WATER'), 'WAGMFBSK 001'),
    (305, external_charge_category_id('WATER'), 'WAMUGFBSK001'),
    (463, external_charge_category_id('WATER'), 'NEO001'),
    (341, external_charge_category_id('WATER'), 'WAMOFBSK002'),
    (470, external_charge_category_id('WATER'), 'WAOTPFBKE001'),
    (473, external_charge_category_id('WATER'), 'WAOMFBKE001'),
    (315, external_charge_category_id('WATER'), 'WABAFBSK001'),
    (398, external_charge_category_id('WATER'), 'WAOGFBFT001'),
    (506, external_charge_category_id('WATER'), ' '),
    (310, external_charge_category_id('WATER'), 'WAOMFBSK 001'),
    (329, external_charge_category_id('WATER'), 'WAALFBSK 001'),
    (319, external_charge_category_id('WATER'), 'WAONFBSK 001'),
    (411, external_charge_category_id('WATER'), 'WAONFBFT002'),
    (418, external_charge_category_id('WATER'), 'WAONFBFT001'),
    (485, external_charge_category_id('WATER'), 'WAPMFBKE001'),
    (421, external_charge_category_id('WATER'), 'WAPUMFBFT001'),
    (419, external_charge_category_id('WATER'), 'WAQUEFBFT001'),
    (327, external_charge_category_id('WATER'), 'WARTFBSK 001'),
    (490, external_charge_category_id('WATER'), 'WASERFBKE001'),
    (482, external_charge_category_id('WATER'), 'WASLFBKE001'),
    (332, external_charge_category_id('WATER'), 'WASSGFBSK001'),
    (416, external_charge_category_id('WATER'), 'WASIFT001'),
    (491, external_charge_category_id('WATER'), 'WATIKE001'),
    (321, external_charge_category_id('WATER'), 'WATSFBSK001'),
    (402, external_charge_category_id('WATER'), 'WAVIFT001'),
    (489, external_charge_category_id('WATER'), 'WAWAFBKE001'),

    ------------------------
    -- UTILITIES Accounts --
    ------------------------
    (278, external_charge_category_id('UTILITIES'), 'WAHEFBSK 001'),
    (487, external_charge_category_id('UTILITIES'), 'UTMOD001'),
    (478, external_charge_category_id('UTILITIES'), 'UTMOT001'),
    (479, external_charge_category_id('UTILITIES'), 'UTND001'),
    (471, external_charge_category_id('UTILITIES'), 'UTKEHA001'),
    (446, external_charge_category_id('UTILITIES'), 'UTKEHA001'),
    (325, external_charge_category_id('UTILITIES'), 'NKH001'),
    (436, external_charge_category_id('UTILITIES'), 'UTOO001'),
    (509, external_charge_category_id('UTILITIES'), 'UTOO001'),
    (535, external_charge_category_id('UTILITIES'), 'UTOO001'),
    (484, external_charge_category_id('UTILITIES'), 'UTPI001'),
    (575, external_charge_category_id('UTILITIES'), 'UTOR01'),
    (506, external_charge_category_id('UTILITIES'), 'UTOR01'),
    (485, external_charge_category_id('UTILITIES'), 'PIN002'),
    (511, external_charge_category_id('UTILITIES'), 'UTPE01'),
    (300, external_charge_category_id('UTILITIES'), 'RERO001'),
    (482, external_charge_category_id('UTILITIES'), 'WASLFBSK001'),
    (274, external_charge_category_id('UTILITIES'), 'STA009'),

    -------------------
    -- RENT Accounts --
    -------------------
    (475, external_charge_category_id('RENT'), 'REAJEW&C001'),
    (494, external_charge_category_id('RENT'), 'REAJEW&C001'),
    (551, external_charge_category_id('RENT'), 'REAF001'),
    (454, external_charge_category_id('RENT'), 'REAI001'),
    (428, external_charge_category_id('RENT'), 'REAI001'),
    (510, external_charge_category_id('RENT'), 'REAI001'),
    (466, external_charge_category_id('RENT'), 'REAI001'),
    (460, external_charge_category_id('RENT'), 'REAI001'),
    (457, external_charge_category_id('RENT'), 'REAI001'),
    (458, external_charge_category_id('RENT'), 'REAI001'),
    (459, external_charge_category_id('RENT'), 'REAI001'),
    (465, external_charge_category_id('RENT'), 'REAI001'),
    (455, external_charge_category_id('RENT'), 'REAI001'),
    (456, external_charge_category_id('RENT'), 'REAI001'),
    (464, external_charge_category_id('RENT'), 'REAI001'),
    (394, external_charge_category_id('RENT'), 'REAI001'),
    (513, external_charge_category_id('RENT'), 'REAI001'),
    (156, external_charge_category_id('RENT'), 'REAI002'),
    (276, external_charge_category_id('RENT'), 'REAVG01'),
    (88, external_charge_category_id('RENT'), 'RESAL01'),
    (381, external_charge_category_id('RENT'), 'REAL001'),
    (307, external_charge_category_id('RENT'), 'REAM001'),
    (273, external_charge_category_id('RENT'), 'REAT001'),
    (472, external_charge_category_id('RENT'), 'REAT001'),
    (359, external_charge_category_id('RENT'), 'REAT001'),
    (437, external_charge_category_id('RENT'), 'REAV001'),
    (424, external_charge_category_id('RENT'), 'REAV001'),
    (385, external_charge_category_id('RENT'), 'REAV001'),
    (422, external_charge_category_id('RENT'), 'REAV001'),
    (429, external_charge_category_id('RENT'), 'REBB002'),
    (364, external_charge_category_id('RENT'), 'REBU001'),
    (443, external_charge_category_id('RENT'), 'REBU001'),
    (280, external_charge_category_id('RENT'), 'REBU001'),
    (383, external_charge_category_id('RENT'), 'REBU001'),
    (268, external_charge_category_id('RENT'), 'REBOI001'),
    (508, external_charge_category_id('RENT'), 'REBORO001'),
    (304, external_charge_category_id('RENT'), 'REBCM001'),
    (170, external_charge_category_id('RENT'), 'REBO02'),
    (365, external_charge_category_id('RENT'), 'REBO001'),
    (503, external_charge_category_id('RENT'), 'REBO001'),
    (294, external_charge_category_id('RENT'), 'REBT001'),
    (294, external_charge_category_id('RENT'), 'REBT001'),
    (431, external_charge_category_id('RENT'), 'REBT001'),
    (299, external_charge_category_id('RENT'), 'REBTO001'),
    (430, external_charge_category_id('RENT'), 'REBR001'),
    (522, external_charge_category_id('RENT'), 'REBRFBMN001'),
    (279, external_charge_category_id('RENT'), 'REBU001'),
    (544, external_charge_category_id('RENT'), 'REBR001'),
    (380, external_charge_category_id('RENT'), 'REBR001'),
    (295, external_charge_category_id('RENT'), 'REBR001'),
    (497, external_charge_category_id('RENT'), 'REBC001'),
    (97, external_charge_category_id('RENT'), 'RECH002'),
    (382, external_charge_category_id('RENT'), 'RECH003'),
    (432, external_charge_category_id('RENT'), 'REKEL001'),
    (504, external_charge_category_id('RENT'), 'REDE001'),
    (552, external_charge_category_id('RENT'), 'REMET001'),
    (434, external_charge_category_id('RENT'), 'REDE002'),
    (296, external_charge_category_id('RENT'), 'REDE002'),
    (333, external_charge_category_id('RENT'), 'REESFBKE001'),
    (361, external_charge_category_id('RENT'), 'REIM001'),
    (587, external_charge_category_id('RENT'), 'REIM002'),
    (306, external_charge_category_id('RENT'), 'REEVFBSK001'),
    (448, external_charge_category_id('RENT'), 'REEV002'),
    (360, external_charge_category_id('RENT'), 'REFA002'),
    (263, external_charge_category_id('RENT'), 'REFNB001'),
    (287, external_charge_category_id('RENT'), 'REFL002'),
    (502, external_charge_category_id('RENT'), 'REFL001'),
    (462, external_charge_category_id('RENT'), 'REGE002'),
    (496, external_charge_category_id('RENT'), 'REAI002'),
    (288, external_charge_category_id('RENT'), 'REGR001'),
    (442, external_charge_category_id('RENT'), 'REGR002'),
    (278, external_charge_category_id('RENT'), 'REHE002'),
    (362, external_charge_category_id('RENT'), 'REHE002'),
    (499, external_charge_category_id('RENT'), 'REHU001'),
    (84, external_charge_category_id('RENT'), 'REIAS001'),
    (449, external_charge_category_id('RENT'), 'REIN001'),
    (480, external_charge_category_id('RENT'), 'RESAM001'),
    (113, external_charge_category_id('RENT'), 'REKL001'),
    (293, external_charge_category_id('RENT'), 'REKF001'),
    (469, external_charge_category_id('RENT'), 'REAK001'),
    (37, external_charge_category_id('RENT'), 'REKE001'),
    (433, external_charge_category_id('RENT'), 'RELEG001'),
    (386, external_charge_category_id('RENT'), 'REMAIR001'),
    (93, external_charge_category_id('RENT'), 'REMA002'),
    (505, external_charge_category_id('RENT'), 'REMA002'),
    (487, external_charge_category_id('RENT'), 'REMOD001'),
    (478, external_charge_category_id('RENT'), 'REMOT001'),
    (450, external_charge_category_id('RENT'), 'REMO003'),
    (468, external_charge_category_id('RENT'), 'REMR001'),
    (285, external_charge_category_id('RENT'), 'REMT001'),
    (153, external_charge_category_id('RENT'), 'REMO002'),
    (349, external_charge_category_id('RENT'), 'REAPJ001'),
    (349, external_charge_category_id('RENT'), 'REAJ001'),
    (427, external_charge_category_id('RENT'), 'REMED005'),
    (427, external_charge_category_id('RENT'), 'REMRI001'),
    (305, external_charge_category_id('RENT'), 'REMUG001'),
    (479, external_charge_category_id('RENT'), 'REND001'),
    (500, external_charge_category_id('RENT'), 'RENW001'),
    (498, external_charge_category_id('RENT'), 'RENWH001'),
    (436, external_charge_category_id('RENT'), 'RENO001'),
    (509, external_charge_category_id('RENT'), 'RENO001'),
    (474, external_charge_category_id('RENT'), 'RENWH001'),
    (484, external_charge_category_id('RENT'), 'REPI001'),
    (575, external_charge_category_id('RENT'), 'RE0KA001'),
    (506, external_charge_category_id('RENT'), 'RE0KA001'),
    (275, external_charge_category_id('RENT'), 'REOR001'),
    (290, external_charge_category_id('RENT'), 'REPR001'),
    (267, external_charge_category_id('RENT'), 'REBP001'),
    (511, external_charge_category_id('RENT'), 'REBP001'),
    (507, external_charge_category_id('RENT'), 'REBP001'),
    (300, external_charge_category_id('RENT'), 'REROL002'),
    (435, external_charge_category_id('RENT'), 'REROL001'),
    (525, external_charge_category_id('RENT'), 'RESAL01'),
    (444, external_charge_category_id('RENT'), 'RESAL01'),
    (495, external_charge_category_id('RENT'), 'RESAL01'),
    (286, external_charge_category_id('RENT'), 'RESF001'),
    (301, external_charge_category_id('RENT'), 'RESHREN001'),
    (303, external_charge_category_id('RENT'), 'RESO002'),
    (50, external_charge_category_id('RENT'), 'RESO001'),
    (332, external_charge_category_id('RENT'), 'RESS001'),
    (274, external_charge_category_id('RENT'), 'RESTD001'),
    (264, external_charge_category_id('RENT'), 'RETH001'),
    (271, external_charge_category_id('RENT'), 'RETR001'),
    (289, external_charge_category_id('RENT'), 'RETS001'),
    (445, external_charge_category_id('RENT'), 'RETS002'),
    (451, external_charge_category_id('RENT'), 'REWE001'),
    (451, external_charge_category_id('RENT'), 'REWEE001'),
    (291, external_charge_category_id('RENT'), 'REWI001'),
    (8, external_charge_category_id('RENT'), 'RESE001'),
    (512, external_charge_category_id('RENT'), 'RESE001'),
    (292, external_charge_category_id('RENT'), 'REWN001'),
    (253, external_charge_category_id('RENT'), 'REWN001'),
    (302, external_charge_category_id('RENT'), 'REW0001');
